name: Lint check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d
        with:
          version: 11

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: "pnpm"

      - name: Lint project
        run: pnpm lint
